# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/108UpEbfH8A0K-3eCc9ea3CJdXujVUJeZ
"""

!pip install -U transliterate

from transliterate import get_available_language_codes
from transliterate import get_translit_function

file_to_read = open("Sirena-export-fixed.tab", "rU")

file_to_write = open( "Sirena-export-fixed_eng.tab", "w" )

translit_ru = get_translit_function('ru')

for row in file_to_read:
    file_to_write.write(translit_ru(row, reversed=True))

file_to_read.close()
file_to_write.close()

def read_first_lines(filename, limit):
  result = []
  with open(filename, 'r') as input_file:
    for line_number, line in enumerate(input_file):
      print(line.split("\t"))
      if line_number > limit:
        break

read_first_lines("Sirena-export-fixed_eng.tab", 100)

